globals = {"Permissions", "Config", "TriggerClientEvent", "json", "AddEventHandler", "RegisterNetEvent",
           "TriggerEvent", "RegisterServerEvent", "LoadResourceFile", "GetCurrentResourceName", "Citizen", "ESX",
           "SaveResourceFile", "TriggerServerEvent", "RegisterCommand", "GetActivePlayers", "GetNumPlayerIndices",
           "GetEntityCoords", "PlayerPedId", "GetDistanceBetweenCoords", "IsPedInAnyVehicle", "GetVehiclePedIsIn",
           "GetVehicleClass", "IsVehicleSirenOn", "GetPedInVehicleSeat", "GetVehicleNumberPlateText", "vector3",
           "GetVehicleColor", "GetEntityModel", "GetHashKey", "GetDisplayNameFromVehicleModel", "GetLabelText",
           "GetEntitySpeed", "GetVehicleModColor1Name", "exports", "SetNotificationTextEntry",
           "AddTextComponentString", "DrawNotification", "RequestModel", "HasModelLoaded", "GetEntityRotation",
           "GetEntityHeading", "CreateObject", "SetEntityRotation", "GetEntityPlayerIsFreeAimingAt",
           "GetActiveScreenResolution", "GetGameplayCamCoord", "GetGameplayCamRot", "GetPlayerPed",
           "GetEntityBoneIndexByName", "GetWorldPositionOfEntityBone", "StartShapeTestRay", "GetShapeTestResult",
           "FreezeEntityPosition", "SetEntityAsMissionEntity", "IsControlJustPressed", "CreateObjectNoOffset",
           "RotationToDirection", "GetScreenCoordFromWorldCoord", "DisablePlayerFiring", "IsPlayerFreeAiming",
           "PlayerId", "DrawLine", "IsPlayerAceAllowed", "PerformHttpRequest", "GetPlayerName", "GetPlayers",
           "GetVehicleColours", "CreateCam", "SetCamCoord", "PointCamAtCoord", "SetCamActive", "RenderScriptCams",
           "AddBlipForCoord", "SetBlipSprite", "SetBlipDisplay", "SetBlipScale", "SetBlipColour",
           "SetBlipAsShortRange", "EndTextCommandSetBlipName", "BeginTextCommandSetBlipName", "Utilities",
           "source", "IsDisabledControlJustPressed", "GetConvar", "GetResourceState", "RemoveBlip",
           "IsDuplicityVersion", "ExecuteCommand", "GetResourcePath", "PerformHttpRequestS", "GetResourceMetadata",
           "NetworkGetEntityOwner", "DeleteObject", "SetEntityCoords", "SetEntityCoordsNoOffset", "GetCgoffset",
           "GetModelDimensions", "PlaceObjectOnGroundProperly", "SetTextCentre", "SetTextOutline", "SetTextEntry",
           "SetTextDropShadow", "SetTextEdge", "SetTextColour", "SetTextProportional", "SetTextFont",
           "SetTextScale", "DrawText", "World3dToScreen2d", "SendNUIMessage", "SetNuiFocus",
           "BeginTextCommandDisplayHelp", "AddTextComponentSubstringTextLabel", "EndTextCommandDisplayHelp",
           "RegisterNUICallback", "AddTextEntry", "RegisterKeyMapping", "DiscordConfig", "IsPedInAnyPoliceVehicle",
           "SendNuiMessage", "GetVehicleCurrentGear", "SetVehicleExtra", "GetPedUsingVehicleDoor",
           "GetPlayerIdentifiers", "SetHttpHandler", "SetConvar"}
exclude_files = {"**/fxmanifest.lua", "sonoran-*/config.CHANGEME.lua"}
std = "max"
ignore = {"211/_.*", "212/_.*", "213/_.*"}
